CREATE TABLE Pay
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT  NOT NULL,
    account_id   BIGINT  NOT NULL,
    item_id      BIGINT  NOT NULL,
    item_name VARCHAR NOT NULL,
    created_at TIMESTAMP,
    account_balance DECIMAL,
    status VARCHAR,
    email VARCHAR,
    total_amount_order DECIMAL
);


drop table Item