CREATE TABLE Account(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name  VARCHAR NOT NULL,
    email        VARCHAR NOT NULL,
    balance      DECIMAL,
    date_created TIMESTAMP,
    last_update  TIMESTAMP
);

drop table Account;