CREATE TABLE Order_DB(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    account_name VARCHAR NOT NULL,
    item_name VARCHAR NOT NULL,
    price_item DECIMAL,
    account_balance DECIMAL,
    quantity_item BIGINT NOT NULL,
    total_amount_order DECIMAL,
    email VARCHAR NOT NULL,
    date_created TIMESTAMP
);

drop table Order_DB;


